services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"

  auth-service:
    build: ./auth-service
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/latacoffee_auth
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-server:
        condition: service_started

  core-service:
    build: ./core-service
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/latacoffee_core
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-server:
        condition: service_started

  api-gateway:
    build: ./api-gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - auth-service
      - core-service

  notification-service:
    build: ./notification-service
    environment:
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - "8083:8083"
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  postgres-data: