spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=core-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://CORE-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/menu/**,/api/reservations/**,/api/orders/**,/api/newsletter/**
eureka.instance.prefer-ip-address=true
