spring.application.name=ai-chat-service
server.port=8085

spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.options.model=claude-sonnet-4-5

jwt.secret=${JWT_SECRET}
spring.ai.anthropic.chat.options.max-tokens=1024
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.hostname=ai-chat-service
eureka.instance.prefer-ip-address=true
