spring.application.name=mcp-server
server.port=8084
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.hostname=mcp-server
eureka.instance.prefer-ip-address=true
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.name=la-ta-coffee-mcp-server
spring.ai.mcp.server.version=1.0.0
jwt.secret=${JWT_SECRET}